import { auth } from "@/auth";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar2 from "@/components/navbar2";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" className="h-full">
        <body className={cn("relative h-full font-sans antialiased", inter.className)}>
          <main className="relative flex flex-col min-h-screen">
            <Navbar2 />
            <div className="flex-grow flex-1">{children}</div>
          </main>
        </body>
      </html>
    </SessionProvider>
  );
}
