import { auth } from "@/auth";
import { ThemeProvider } from "@/components/settings/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Toaster as DefaultToaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" className="h-full">
        <body
          className={cn(
            "relative h-full font-sans antialiased",
            inter.className
          )}
        >
          <ThemeProvider attribute="class">
            <NextUIProvider>
              <main className="bg-background">
                <div className="">{children}</div>
              </main>
            </NextUIProvider>
            <Toaster />
            <DefaultToaster />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
